// Writes the logo geometry as a TypeScript module for the app.
import fs from 'node:fs';
import { heavyFa, heavyRender, H } from './heavy.mjs';
import { glyph } from './icon.mjs';
const r = heavyRender(heavyFa(), { ink: 'INK', acc: 'ACC' });
const d = {}; for (const m of r.body.matchAll(/<path fill="(INK|ACC)" d="([^"]+)"\/>/g)) d[m[1]] = m[2];
const g = glyph(100, { c1: 'B1', c2: 'B2', c3: 'PL' });
const gd = {}; for (const m of g.matchAll(/<path fill="(B1|B2|PL)"[^d]*d="([^"]+)"\/>/g)) gd[m[1]] = m[2];
const out = `// Generated by brand/src/tsgen.mjs: the custom lettering and the app icon glyph. Do not edit by hand.

/** «بک‌تست‌لب» lettering. \`ink\` is «بک‌تست», \`accent\` is «لب». */
export const WORDMARK = {
  width: ${+r.vbw.toFixed(2)},
  height: ${+r.vbh.toFixed(2)},
  /** top of the tallest letters to the baseline (the rest is the dots below) */
  ascent: ${H.A},
  ink: '${d.INK}',
  accent: '${d.ACC}',
} as const;

/** Icon glyph on a 100 × 100 tile: two rising bars and the play button. */
export const MARK = {
  bar1: '${gd.B1}',
  bar2: '${gd.B2}',
  play: '${gd.PL}',
} as const;
`;
fs.writeFileSync(process.argv[2], out);
console.log(Object.keys(d), Object.keys(gd), r.vbw.toFixed(1), r.vbh.toFixed(1));
